batches/urls.py
from django.conf.urls import url

from . import views

app_name = 'batches'

urlpatterns = [
    url(r'^', views.BatchesListView.as_view(), name='list'),
]

reposeacademy/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from cms.views import about_us
from reposeforms.views import CourseEnquiryView, ThankYouView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^', include('default.urls', namespace='default')),
    url(r'^contactus/', include('contactus.urls')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^branches/', include('branches.urls', namespace='branches')),
    url(r'^about_us/', about_us),
    url(r'^batches/', include('batches.urls', namespace='batches')),
    url(r'^course_enquiry/', CourseEnquiryView.as_view(), name='course_enquiry'),
    url(r'^thanks/',ThankYouView.as_view())

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gallery/models.py
# -*- coding: utf-8 -*-
# Copyright (c) Zbigniew Siciarz 2012-2016.

from __future__ import unicode_literals

from PIL import Image, ExifTags

from django.conf import settings
from django.db import connection, models
from django.db.models.query import QuerySet
from django.utils.encoding import python_2_unicode_compatible
from django.utils import six
from django.utils.translation import ugettext_lazy as _

from model_utils import Choices
from model_utils.models import StatusModel, TimeStampedModel


def sanitize_exif_value(key, value):
    if isinstance(value, six.string_types):
        return value.replace('\x00', '').strip()
    return str(value)


class GalleryQuerySet(QuerySet):
    def published(self):
        return self.filter(status='published')



@python_2_unicode_compatible
class Gallery(StatusModel, TimeStampedModel):
    STATUS = Choices(
            ('draft', _("draft")),
            ('published', _("published")),
    )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False, verbose_name=_("author"),
                               on_delete=models.CASCADE)
    title = models.CharField(_("title"), max_length=255)
    slug = models.SlugField(_("slug"), max_length=255, unique=True)
    description = models.TextField(_("description"))
    shot_date = models.DateField(_("shot date"), null=True, blank=True)
    cover_photo = models.ImageField(_("cover photo"), upload_to='photos/%Y/%m/%d', null=True, blank=True)

    objects = GalleryQuerySet.as_manager()

    class Meta:
        verbose_name_plural = _("Galleries")
        ordering = ['-shot_date']

    def __str__(self):
        """
        The string representation of a gallerynotinuse is its title.
        """
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('gallery:gallery_details', [], {'slug': self.slug})

    def get_teaser_photos(self):
        return self.photos.all()[:4]


class PhotoManager(models.Manager):
    def tagged(self, tag):
        return self.filter(tags__contains=[tag]).order_by('-gallery__shot_date')

    def for_exif(self, exif_key, exif_value):
        return self.filter(exif__contains={exif_key: exif_value}).order_by('-gallery__shot_date')

    def popular_tags(self, count=10):
        query = """
        select
            t.tag,
            count(t.tag) as tag_count
        from
            (select unnest(tags) as tag from %s) t
        group by tag
        order by tag_count desc
        limit %%s
        """ % Photo._meta.db_table
        cursor = connection.cursor()
        cursor.execute(query, (count,))
        tags = [{'tag': row[0], 'count': row[1]} for row in cursor.fetchall()]
        return tags


@python_2_unicode_compatible
class Photo(TimeStampedModel):
    gallery = models.ForeignKey(Gallery, null=True, related_name='photos', verbose_name=_("gallery"),
                                on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False, verbose_name=_("author"),
                               on_delete=models.CASCADE)
    title = models.CharField(_("title"), max_length=255)
    image = models.ImageField(_("image"), upload_to='photos/%Y/%m/%d')

    objects = PhotoManager()

    class Meta:
        verbose_name_plural = _("Photos")
        ordering = ['created']

    def __str__(self):
        """
        The string representation of a photo is its title.
        """
        return self.title

    def save(self, *args, **kwargs):
        """
        Updates EXIF data before saving.
        """
        # you really should be doing this in a background task
        try:
            img = Image.open(self.image.file)
            raw_exif = img._getexif()
            if raw_exif:
                self.exif = {ExifTags.TAGS[k]: sanitize_exif_value(k, v) for k, v in raw_exif.items() if
                             k in ExifTags.TAGS}
        except Exception:
            pass
        super(Photo, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('gallery:photo_details', [], {'pk': self.pk})

    def get_next_photo(self):
        """
        Returns next photo from the same gallerynotinuse (in chronological order).

        Wraps around from last photo in the gallerynotinuse to the first one.
        """
        try:
            next_photo = Photo.objects.filter(
                    gallery=self.gallery,
                    created__gt=self.created,
            )[0]
        except IndexError:
            next_photo = Photo.objects.filter(gallery=self.gallery)[0]
        return next_photo

    def get_previous_photo(self):
        """
        Returns previous photo from the same gallerynotinuse (in chronological order).

        Wraps around from first photo in the gallerynotinuse to the last one.
        """
        try:
            previous_photo = Photo.objects.filter(
                    gallery=self.gallery,
                    created__lt=self.created,
            ).latest('created')
        except Photo.DoesNotExist:
            previous_photo = Photo.objects.filter(gallery=self.gallery).latest('created')
        return previous_photo


@python_2_unicode_compatible
class Video(TimeStampedModel):
    gallery = models.ForeignKey(Gallery, null=True, related_name='videos', verbose_name=_("gallery"),
                                on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False, verbose_name=_("author"),
                               on_delete=models.CASCADE)
    title = models.CharField(_("title"), max_length=255)
    file = models.FileField(upload_to='videos/%Y/%m/%d')

    class Meta:
        verbose_name_plural = _("Videos")
        ordering = ['created']

templates/gallerynotinuse/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>

<body>
    <div class="container">
        <header class="page-header">
        </header>
        <div class="row">
            {% block base-content %}{% endblock %}
        </div>
    </div>
</body>
</html>

templates/gallerynotinuse/base_photos.html
{% extends "pgallery/base.html" %}
{% load i18n %}
{% load pgallery_tags %}

{% block base-content %}
    <div class="col-lg-9">
        {% block content %}{% endblock %}
    </div>
    <div class="col-lg-3">
        <section class="recent-galleries">
            <h2>{% trans 'Recent galleries' %}</h2>
            <ul>
                {% get_recent_galleries 10 as recent_galleries %}
                {% for gallery in recent_galleries %}
                    <li><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></li>
                {% endfor %}
            </ul>
        </section>
        <section class="archive">
            <h2>{% trans "Archive" %}</h2>
            <ul>
                {% get_gallery_archive_dates as dates %}
                {% for date in dates %}
                    <li><a href="{% url 'pgallery:month_archive' year=date.year month=date.month %}">{{ date|date:"F Y" }}</a></li>
                {% endfor %}
            </ul>
        </section>
        <section class="popular-tags">
            <h2>{% trans "Popular tags" %}</h2>
            <ul>
                {% get_popular_tags as tags %}
                {% for tag in tags %}
                    <li><a href="{% url 'pgallery:tagged_photo_list' tag=tag.tag %}" rel="tag">{{ tag.tag }}</a></li>
                {% endfor %}
            </ul>
        </section>
    </div>
{% endblock %}

templates/gallerynotinuse/exif_photo_list.html
{% extends "pgallery/base_photos.html" %}
{% load i18n %}

{% block content %}
    <article>
        <h1>{{ exif_key }}: {{ exif_value }}</h1>
        {% include "pgallery/thumbnail_list.html" %}
    </article>
{% endblock %}

templates/gallerynotinuse/gallery_archive_month.html
{% extends "pgallery/gallery_list.html" %}

{% block title %}{{ month|date:"F Y" }} | {{ block.super }}{% endblock %}
{% block og-title %}{{ month|date:"F Y" }} | {{ block.super }}{% endblock %}

templates/gallerynotinuse/gallery_detail.html
{% extends "pgallery/base_photos.html" %}
{% load i18n %}

{% block content %}
    <article>
        <h1>{{ gallery.title }}</h1>
        {% include "pgallery/gallery_menu.html" %}
        {{ gallery.description }}
        {% include "pgallery/thumbnail_list.html" with photo_list=gallery.photos.all %}
        </ul>

        <footer>
            {% trans 'Added on' %} {{ gallery.shot_date|date:"DATE_FORMAT" }}
        </footer>
    </article>
{% endblock %}

templates/gallerynotinuse/gallery_list.html
{% extends "pgallery/base_photos.html" %}
{% load i18n %}

{% block content %}
    {% for gallery in gallery_list %}
        <article>
            <h1><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></h1>
            {% include "pgallery/thumbnail_list.html" with photo_list=gallery.get_teaser_photos %}

            <footer>
                {% trans "added on" %} {{ gallery.shot_date|date:"DATE_FORMAT" }}
            </footer>
        </article>
    {% empty %}
        <p>{% trans "There aren't any galleries." %}</p>
    {% endfor %}
{% endblock %}

templates/gallerynotinuse/gallery_menu.html
{% load i18n %}

    {% if user.is_staff %}
        <span class="label label-info">{{ gallery.get_status_display }}</span>
        <a href="{% url 'admin:pgallery_gallery_change' gallery.id %}">{% trans "Edit" %}</a>
    {% endif %}

templates/gallerynotinuse/photo_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block base-content %}
    <div class="col-md-9">
        <article>
        <a href="{{ photo.get_next_photo.get_absolute_url }}">
                <img class="img-responsive" src="{{ photo.image.url }}" alt="{{ photo.title }}" />
            </a>
            <section>
                <h2>{% trans "Exif data" %}</h2>
                <table class="table table-condensed">
                    <thead>
                    </thead>
                    <tbody>
                    {% for key, value in photo.exif.items %}
                        <tr>
                            <th>{{ key }}</th>
                            <td><a href="{% url 'pgallery:exif_photo_list' exif_key=key exif_value=value %}">{{ value }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </section>
        </article>
    </div>
    <div class="col-md-3">
        <section>
            <h2><a href="{{ photo.gallery.get_absolute_url }}">{{ photo.gallery.title }}</a></h2>
            {{ photo.title }}
            <div>
                {% trans "Tags" %}:
                {% for tag in photo.tags %}
                    <a href="{% url 'pgallery:tagged_photo_list' tag=tag %}" rel="tag">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock %}

templates/gallerynotinuse/photo_list.html
{% extends "pgallery/base_photos.html" %}
{% load i18n %}

{% block content %}
    <article>
        <h1>{% trans "Tag" %}: {{ tag }}</h1>
        {% include "pgallery/thumbnail_list.html" %}
    </article>
{% endblock %}

templates/gallerynotinuse/thumbnail_list.html
{% load i18n %}

<ul class="thumbnails">
    {% for photo in photo_list %}
    <li>
        <a class="thumbnail" title="{{ photo.title }}" href="{{ photo.get_absolute_url }}">
            <img src="{{ photo.image.url }}" alt="{{ photo.title }}" width="200" height="200" />
            <span class="description">{{ photo.title }}</span>
        </a>
    </li>
    {% endfor %}
</ul>